from enum import Enum


class SymbolInfoArraysTimezoneItem(str, Enum):
    AFRICAJOHANNESBURG = "Africa/Johannesburg"
    AMERICAARGENTINABUENOS_AIRES = "America/Argentina/Buenos_Aires"
    AMERICABOGOTA = "America/Bogota"
    AMERICACHICAGO = "America/Chicago"
    AMERICAEL_SALVADOR = "America/El_Salvador"
    AMERICALOS_ANGELES = "America/Los_Angeles"
    AMERICAMEXICO_CITY = "America/Mexico_City"
    AMERICANEW_YORK = "America/New_York"
    AMERICAPHOENIX = "America/Phoenix"
    AMERICASAO_PAULO = "America/Sao_Paulo"
    AMERICATORONTO = "America/Toronto"
    AMERICAVANCOUVER = "America/Vancouver"
    ASIAALMATY = "Asia/Almaty"
    ASIAASHKHABAD = "Asia/Ashkhabad"
    ASIABANGKOK = "Asia/Bangkok"
    ASIADUBAI = "Asia/Dubai"
    ASIAHONG_KONG = "Asia/Hong_Kong"
    ASIAKATHMANDU = "Asia/Kathmandu"
    ASIAKOLKATA = "Asia/Kolkata"
    ASIASEOUL = "Asia/Seoul"
    ASIASHANGHAI = "Asia/Shanghai"
    ASIASINGAPORE = "Asia/Singapore"
    ASIATAIPEI = "Asia/Taipei"
    ASIATEHRAN = "Asia/Tehran"
    ASIATOKYO = "Asia/Tokyo"
    AUSTRALIAACT = "Australia/ACT"
    AUSTRALIAADELAIDE = "Australia/Adelaide"
    AUSTRALIABRISBANE = "Australia/Brisbane"
    AUSTRALIASYDNEY = "Australia/Sydney"
    ETCUTC = "Etc/UTC"
    EUROPEATHENS = "Europe/Athens"
    EUROPEBERLIN = "Europe/Berlin"
    EUROPELONDON = "Europe/London"
    EUROPEMADRID = "Europe/Madrid"
    EUROPEMOSCOW = "Europe/Moscow"
    EUROPEPARIS = "Europe/Paris"
    EUROPEWARSAW = "Europe/Warsaw"
    PACIFICAUCKLAND = "Pacific/Auckland"
    PACIFICCHATHAM = "Pacific/Chatham"
    PACIFICFAKAOFO = "Pacific/Fakaofo"
    PACIFICHONOLULU = "Pacific/Honolulu"
    USMOUNTAIN = "US/Mountain"

    def __str__(self) -> str:
        return str(self.value)
